# bambu_defs.py
# Shared definitions for Bambu Lab printer status codes.
# Sourced from:
#  - OrcaSlicer: https://github.com/SoftFever/OrcaSlicer/blob/4d762c4e91f33a33442b3725ef17d5d323db62d5/src/slic3r/GUI/DeviceManager.cpp#L78
#  - Home Assistant integreation: https://github.com/greghesp/ha-bambulab/blob/main/custom_components/bambu_lab/pybambu/const.py

STAGE_DESCRIPTIONS = {
    -1:  "Idle",
    0:   "Printing",
    1:   "Auto bed leveling",
    2:   "Heatbed preheating",
    3:   "Sweeping XY mech mode",
    4:   "Changing filament",
    5:   "M400 pause",
    6:   "Paused due to filament runout",
    7:   "Heating hotend",
    8:   "Calibrating extrusion",
    9:   "Scanning bed surface",
    10:  "Inspecting first layer",
    11:  "Identifying build plate type",
    12:  "Calibrating Micro Lidar",
    13:  "Homing toolhead",
    14:  "Cleaning nozzle tip",
    15:  "Checking extruder temperature",
    16:  "Printing was paused by the user",
    17:  "Pause of front cover falling",
    18:  "Calibrating the micro lida",
    19:  "Calibrating extrusion flow",
    20:  "Paused due to nozzle temperature malfunction",
    21:  "Paused due to heat bed temperature malfunction",
    22:  "Filament unloading",
    23:  "Skip step pause",
    24:  "Filament loading",
    25:  "Motor noise calibration",
    26:  "Paused due to AMS lost",
    27:  "Paused due to low speed of the heat break fan",
    28:  "Paused due to chamber temperature control error",
    29:  "Cooling chamber",
    30:  "Paused by the Gcode inserted by user",
    31:  "Motor noise showoff",
    32:  "Nozzle filament covered detected pause",
    33:  "Cutter error pause",
    34:  "First layer error pause",
    35:  "Nozzle clog pause",
    36:  "Check absolute accuracy before calibration",
    37:  "Absolute accuracy calibration",
    38:  "Check absolute accuracy after calibration",
    39:  "Calibrate nozzle offset",
    40:  "Bed level high temperature",
    41:  "Check quick release",
    42:  "Check door and cover",
    43:  "Laser calibration",
    44:  "Check plaform",
    45:  "Check birdeye camera position",
    46:  "Calibrate birdeye camera",
    47:  "Bed level phase 1",
    48:  "Bed level phase 2",
    49:  "Heating chamber",
    50:  "Heated bedcooling",
    51:  "Print calibration lines",
    255: "Idle",
    }
